Train:
  batch_size: 64
  learning_rate: 0.5
  reg: 0.001
  epochs: 20
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 128 # only applicable for TwolayerNet
